[build-system]
requires = ["intreehooks", "wheel", "meson", "pytoml",]
build-backend = "intreehooks:loader"

[tool.intreehooks]
build-backend = "mesonpep517.buildapi"

[tool.mesonpep517.metadata]
module="mesonpep517"
summary="Create pep517 compliant builds from the meson build system"
author="Thibault Saunier"
author-email="tsaunier@gnome.org"
home-page="https://gitlab.com/thiblahute/mesonpep517"
requires=[
    "wheel",
    "meson",
]
requires-python="3"
description-file="README.md"
classifiers = [
    "Intended Audience :: Developers",
    "License :: OSI Approved :: Apache Software License",
    "Programming Language :: Python :: 3",
    "Topic :: Software Development :: Libraries :: Python Modules",
]
requires_dist = ["wheel", "meson", "pytoml",]